In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [26]:
df=pd.read_csv('Titanic.csv')[['Survived','Fare','Age','Pclass']]

In [27]:
df

     Survived     Fare   Age  Pclass
0           0   7.2500  22.0       3
1           1  71.2833  38.0       1
2           1   7.9250  26.0       3
3           1  53.1000  35.0       1
4           0   8.0500  35.0       3
..        ...      ...   ...     ...
886         0  13.0000  27.0       2
887         1  30.0000  19.0       1
888         0  23.4500   NaN       3
889         1  30.0000  26.0       1
890         0   7.7500  32.0       3

[891 rows x 4 columns]

In [28]:
df.head()

   Survived     Fare   Age  Pclass
0         0   7.2500  22.0       3
1         1  71.2833  38.0       1
2         1   7.9250  26.0       3
3         1  53.1000  35.0       1
4         0   8.0500  35.0       3

In [29]:
df.isnull().mean()*100

Survived     0.00000
Fare         0.00000
Age         19.86532
Pclass       0.00000
dtype: float64

In [30]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:
x_train

         Fare   Age  Pclass
331   28.5000  45.5       1
733   13.0000  23.0       2
382    7.9250  32.0       3
704    7.8542  26.0       3
813   31.2750   6.0       3
..        ...   ...     ...
106    7.6500  21.0       3
270   31.0000   NaN       1
860   14.1083  41.0       3
435  120.0000  14.0       1
102   77.2875  21.0       1

[712 rows x 3 columns]

In [33]:
knn=KNNImputer()   # inside the knnimputer the paraeter called nabours if we change it they will change our value
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.fit_transform(x_test)

In [34]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

         Fare   Age  Pclass
0     28.5000  45.5     1.0
1     13.0000  23.0     2.0
2      7.9250  32.0     3.0
3      7.8542  26.0     3.0
4     31.2750   6.0     3.0
..        ...   ...     ...
707    7.6500  21.0     3.0
708   31.0000  39.0     1.0
709   14.1083  41.0     3.0
710  120.0000  14.0     1.0
711   77.2875  21.0     1.0

[712 rows x 3 columns]

In [35]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)     # apply the logitic regreesion on knn impute data
accuracy_score(y_pred,y_test)

0.7486033519553073

In [36]:
knn=KNNImputer(weights='distance')   
x_train_trf=knn.fit_transform(x_train)     # now we used the parmeter weights=ditanse they imprve our accuarcy from privious one
x_test_trf=knn.fit_transform(x_test)
pd.DataFrame(x_train_trf,columns=x_train.columns)

         Fare        Age  Pclass
0     28.5000  45.500000     1.0
1     13.0000  23.000000     2.0
2      7.9250  32.000000     3.0
3      7.8542  26.000000     3.0
4     31.2750   6.000000     3.0
..        ...        ...     ...
707    7.6500  21.000000     3.0
708   31.0000  40.111111     1.0
709   14.1083  41.000000     3.0
710  120.0000  14.000000     1.0
711   77.2875  21.000000     1.0

[712 rows x 3 columns]

In [37]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)     
accuracy_score(y_pred,y_test)

0.7541899441340782

In [38]:
# now we will try simpleimputer mean t cheak is acuracy is increse or not
si=SimpleImputer()
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [40]:
lr=LogisticRegression()
lr.fit(x_train_trf2,y_train)
y_pred2=lr.predict(x_test_trf2)
accuracy_score(y_pred2,y_test)   # see the accuracy f simple imputer which is less than knn imputer

0.7374301675977654